sbt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path
from restapi.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', lambda r: HttpResponseRedirect('sbt/')),
    path('sbt/', include('website.urls')),
    path('auth/', include('authentication.urls')),
    path('api/', include('restapi.urls',namespace='rest_api')),
    path('vendor/', include('Vendor.urls')),
    path('employee/', include('Employee.urls',namespace='employee')),
    path('customer/', include('Customer.urls')),
    path('sbtadmin/', include('dashboard.urls',namespace='dashboard')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = 'website.views.error_404_view'

website/urls.py
from django.urls import path,include
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

#Django Admin Header customization
admin.site.site_header = "SBT Professionals"
admin.site.site_title = "Dashboard- SBT Professionals"
admin.site.index_title = "Welcome To SBT Professionals"

app_name = 'website'

urlpatterns = [




    # path('inf_scroll', views.ArticlesView.as_view()),
    # path("test/<int:slug>", views.test, name="test"),

    path("test", views.test, name="test"),
    # path('ankit-test', views.template_test, name="ankit-test"),

    path('loc', views.location, name='location'),

    path('suggestions', views.suggestions, name='suggestions'),
    path('query', views.query, name='query'),
    path('create', views.create, name = "create"),
    path('format', views.format, name='format'),
    path("", views.index, name='Sbthome'),
    path("vendor_review_test", views.vendor_review),

    path('top_vendor_details/<str:slug>', views.top_vendor_details, name='top-details'),
    path("become_a_vendor/", views.freelisting, name='listing'),
    path("top/", views.top, name='top'),
    path("membership/", views.customer_membership, name='membership'),
    path("jobs/", views.jobs, name='jobs'),
    path("search/", views.search, name='search'),
    path("upload_resume/", views.upload_resume, name='upload_resume'),
    path("download/", views.download, name='download'),
    path("trading/", views.trading, name='trading'),
    path("process/", views.process, name='process'),
    path("FAQ/", views.faq, name='faq'),
    path("top/", views.top, name='top'),
    path("search_top/", views.search_top, name='search_top'),
    path("frenchise/", views.frenchise, name='frenchise'),
    path("topvendors/<str:slug>", views.single_vendor, name='single_vendor'),
    path("categories/<str:slug>", views.categories, name='categories'),
    path("subcategories/<str:slug>", views.sub_to_sub_category, name='sub_to_sub_category'),
    path("contactservice/<str:slug>", views.contact_via_service, name="contactservice"),
    path("services/<str:slug>", views.service_detail, name='service_detail'),
    path('newsletter/', views.newsletter, name='newsletter'),
    path('feedback/', views.feedback, name='feedback'),
    path('TermsCondition/', views.tac, name='Terms_and_condition'),
#     path('username_validator', views.username_validator, name="uv"),"""


    # Payment, Purchase, Order Urls
    path("purchase_customer/<int:slug>", views.purchase_customer, name="plan-purchase"),
    # path("purchase_vendor/<int:slug>", views.purchase_vendor, name="vendor-purchase"),
    path("customer_card_purchase/<int:plan_id>", views.customer_card_purchase, name='card-purchase'),
    path('pricing-multiplier/', views.pricing_multiplier, name ="PM"),
    path('req_handler', views.req_handler, name='Request Handler'),
    path('order_status/<str:slug>', views.order_status, name='Order_Status'),
    # Authentication Urls
#     path('signup/', views.sign_up, name='SignUp'),
    path('login/', views.log_in, name='login'),
    path('verify/', views.verify, name='verify'),
    path('logout/', views.logout_view, name='Logout'),
#     path('signup/', views.sign_up, name='SignUp'),
#     path('login/', views.log_in, name='Login'),
#     path('logout/', views.logout_view, name='Logout')

    path('refund_policy', views.refund_policy, name = 'refund-policy'),
    path('privacy_policy', views.privacy_policy, name = 'privacy-policy'),
    # Password Reset Urls
#     path('reset_password/',
#          auth_views.PasswordResetView.as_view
#          (template_name='website/password_reset.html'),
#          name='password_reset'),
#     path('reset_password_sent/',
#          auth_views.PasswordResetDoneView.as_view
#          (template_name='website/password_reset_Sent.html'),
#          name='password_reset_done'),
#     path('reset/<uidb64>/<token>',
#          auth_views.PasswordResetConfirmView.as_view
#          (template_name='website/password_reset_form.html'),
#          name='password_reset_confirm'),
#     path('reset_password_complete/',
#          auth_views.PasswordResetCompleteView.as_view
#          (template_name='website/password_reset_done.html'),
#          name='password_reset_complete'),
    ]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/views.py
from Customer.models import *
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import HttpResponse, redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from geopy.geocoders import Nominatim
from Vendor.models import KeyWord, Vendor, VendorServices
from django.core.mail import EmailMessage
from .DummyData import DummyData

# To import for login,Signup
"""
from django.contrib.auth.models import User
"""

import json
import math
import random
import re
import requests
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
# validations
from django.core.validators import validate_email
from django.http import JsonResponse

#importing func from function.py
from .functions import *
from .models import *
# FOR PAYTM---------------------
from .PayTm import CheckSum
from .validations import *



# FOR PAYTM End-----------------------------------
# TODO
    # Need to create a function which change configuration of backend as well as frontend using our config.json
    # Nedd to add a order id function


# ! NEVER SHOW MERCHANT ID AND KEY !
MID = "bPYtDh39113697597251"  # MERCHANT ID
MKEY = "YX24Rc1vgjPCPs5@"  # MERCHANT KEY

fn = pathlib.Path(__file__).parent.parent / 'config.json'
with open(fn,"r") as params:
    parameters = json.load(params)

# def vendor_profile(request):
#     return render(request, 'template_name.html')
def menu_top(request):
    tops = TOP.objects.all()
    return {'TOPS': tops}

def vendor_profile(request):
    return render(request, 'website/vendor-profile.html')

def index(request):
    category = Categories.objects.all()
    # Logic for services
    services = Service.objects.all()

    # testimonials
    testimonials = AddTestimonial.objects.all()

    plans = Plan.objects.all()
    return render(request, 'website/index.html',
                  {'plans': plans, 'category': category, 'services': services,'testimonials':testimonials})

# Function to take input from form and send it through email
def freelisting(request):
    category = Categories.objects.all()
    if request.method == 'POST':
        # Validate
        resp = form_validation(request.POST)
        if resp != None:
            messages.warning(request,resp)
            return redirect('website:listing')
        Company_name = request.POST.get('companyname', '')
        location = request.POST.get('location', '')
        first_name = request.POST.get('firstname', '')
        last_name = request.POST.get('lastname', '')
        city = request.POST.get('city', '')
        state = request.POST.get('state', '')
        zip_code = request.POST.get('zip_code', '')
        mobile = request.POST.get('phone', '')
        email = request.POST.get('email', '')
        # send mail function from django.core.mail import send mail
        send_mail(
            subject='New Vendor registered',
            message=f"Company Name = {Company_name}\nName = {first_name + ' ' + last_name}\nMobile No. = {mobile}\nAddress = {city + ',' + state + ',' + zip_code}",
            from_email= parameters['from_email'],
            recipient_list=[parameters['to_email']],
            fail_silently=False
            # contact@sbtprofessionals.com
            # teamofprofessionals2015@gmail.com
        )
        # checks on values of form and using django.contrib import message for alert messages
        if Company_name:

            listing = FreeListing(Company_name=Company_name, location=location, first_name=first_name,
                                  last_name=last_name, city=city, state=state, zip_code=zip_code, mobile=mobile,
                                  email=email)
            listing.save()
            messages.success(request, 'Form submission successful. SBT Professional team Contact You within 24'
                                      'hours.')
            return redirect('website:Sbthome')
    return render(request, 'website/forms/freelisting.html', {'category': category})


def customer_membership(request):
    category = Categories.objects.all()
    redirect1 = '/sbt/purchase'

    plans = Plan.objects.all()

    return render(request, 'website/pages/membership.html', {'plans': plans, 'category': category,'redirect':redirect1})


def jobs(request):
    category = Categories.objects.all()
    if request.method == "POST":
        name = request.POST.get('contactName', '')
        mobile = request.POST.get('contactmobile', '')
        education = request.POST.get('contactEducation', '')
        experience = request.POST.get('contactexperience', '')
        # checks on values of form and using django.contrib import message for alert messages
        resume = Job(name=name, mobile=mobile,
                     education=education, experience=experience)

        resume.save()
        messages.success(request, 'Form submission successful. SBT Professional team Contact You within '
                                  '24 hours.')
        send_mail(
            subject='New Job seeker created resume',
            message=f"Employee Name = {name}\nMobile No. = {mobile}\nExperience = {experience}\nEducation = {education}",
            from_email= parameters['from_email'],
            recipient_list=[parameters['to_email']],
            fail_silently=False
            # contact@sbtprofessionals.com
            # teamofprofessionals2015@gmail.com
        )
        return render(request, 'website/forms/job_form.html', {'category': category})

    return render(request, 'website/forms/job_form.html', {'category': category})


def upload_resume(request):
    category = Categories.objects.all()
    if request.method == "POST":
        name = request.POST.get('contactName', '')
        uploaded_resume = request.FILES['myfile']
        if name:
            resume = Upload_resume(name=name, Resume=uploaded_resume)
            resume.save()
            fs = FileSystemStorage()
            fs.save(uploaded_resume.name, uploaded_resume)
            messages.success(request,
                                'Resume submission successful. SBT Professional team Contact You within 24 hours.')
            try:
                file = settings.MEDIA_URL[1:] + str(uploaded_resume)
                
                msg = EmailMessage('New job Seeker on your website', 'name =' + name, parameters['from_email'],
                                    [parameters['to_email']])
                msg.attach_file(file)
                msg.send()
            except:
                messages.error(request,'Failed to uplaod Resume! Try Again.')
                return redirect('website:Sbthome')
        else:
            messages.error(request, 'Before submit Resume Please Enter your name')

    return render(request, 'website/forms/job_form.html', {'category': category})

def download(request):
    category = Categories.objects.all()
    if request.method == 'POST':
        number = request.POST.get('number')
        if number.isnumeric():
            send_sms_message(number)
            messages.success(request,'Link sent successfully check your inbox!')
            return redirect('website:Sbthome')
        else:
            messages.warning(request,'Enter a number!')
            return render(request, 'website/pages/downloadapp.html', {'category': category})
    return render(request, 'website/pages/downloadapp.html', {'category': category})


def categories(request, slug):
    category = Categories.objects.all()
    filtered_categories = Categories.objects.filter(category_name=slug)
    related_sub_category = Subcategory.objects.all().filter(category_name__in=filtered_categories)
    return render(request, 'website/pages/category.html',
                  {'filtered_categories': filtered_categories, 'sub_category': related_sub_category,
                   'category': category})


def sub_to_sub_category(request, slug):
    category = Categories.objects.all()
    related_sub_category = Subcategory.objects.all().filter(sub_category_name=slug)
    related_sub_sub_category = Sub_sub_category.objects.all().filter(sub_category_name__in=related_sub_category)
    params = {'slug': slug}
    if related_sub_sub_category.exists():
        return render(request, 'website/pages/subcategory.html',
                      {'sub_category': related_sub_category, 'related_sub_sub_category': related_sub_sub_category,
                       'category': category})
    else:
        return render(request, 'website/forms/contact_via_category.html', {'slug': slug, 'category': category})



def test(request):
    if request.method =="POST":
        resp = form_validation(request.POST)
        return HttpResponse(f"nahi chala{resp}")

    return render(request, 'website/auth_and_pass/test.html')

@login_required(login_url="website:login")
def purchase_vendor(request, slug):
    category = Categories.objects.all()
    plan = Plan.objects.get(plan_id =slug)

    dict_for_review = {
        'id' : plan.plan_id,
        'name': plan.plan_name,
        'amount': plan.plan_amount,
        'description_1': plan.description_1,
        'description_2': plan.description_2,
        'description_3': plan.description_3,
        'description_4': plan.description_4,
    }
    return render(request, 'website/forms/purchase_form_customer.html', {'plan_review': dict_for_review, 'category': category})


@login_required(login_url="website:login")
def purchase_customer(request, slug):# plan_id, user, amount,discount,role):
    category = Categories.objects.all()


    plan = Plan.objects.get(plan_id =slug)
    dict_for_review = {
        'id' : plan.plan_id,

website/templates/website/includes/footer.html
<footer id="footer">
    <div class="footer-top">
      <!-- .container -->
      <div class="container">
        <div class="row">
          <div class="col-xl-3 col-lg-4 col-sm-6">
            <!-- footer widget -->
            <div class="f-widget-title">
              <h4>SBT Professional</h4>
            </div>
            <div class="sigle-address">
              <div class="address-icon">
                <i class="fas fa fa-home"></i>
              </div>
              <address>
                office Address :SCO 152, 2nd floor,Mughal Canal (KNL) HR -132001</address>
            </div>
            <div class="sigle-address">
              <div class="address-icon">
                <i class="far fa-envelope-open"></i>
              </div>
              <p>contact@sbtprofessionals.com</p>
            </div>
            <div class="sigle-address">
              <div class="address-icon">

              </div>

            </div>
          </div>
          <!-- footer widget -->
          <div class="col-xl-2 offset-xl-1 col-lg-3 col-sm-6">
            <!-- footer widget -->
            <div class="f-widget-title">

              <h4>Contact us </h4> </i>
            </div>
            <div class="f-widget-link" style="color: white;font-size: 13px;width: 363px;">
              <ul>
                <!-- Menu Link -->
                <li> <i class="fas fa-headphones"></i>
                  +91 8295393035 </li>
              </ul>
            </div>
          </div>
          <!-- footer widget -->
          <div class="col-xl-2 offset-xl-1 col-lg-3 col-sm-6">
            <!-- footer widget -->
            <div class="f-widget-title">
              <h4>TOP BRANCHES</h4>
            </div>
            <div class="f-widget-link">
              <ul>
                <!-- Menu Link -->
                <li><a href="#Gurugram">Gurugram(Head Office)</a></li>
                <li><a href="#Panipat">Panipat</a></li>
                <li><a href="#Karnal">karnal</a></li>
                <li><a href="#Zirakpur">Zirakpur</a></li>
              </ul>
            </div>
          </div>
          
          <div class="col-xl-2 offset-xl-1 col-lg-3 col-sm-6">
            <!-- footer widget -->
            <div class="f-widget-title">
              <h4>Policies</h4>
            </div>
            <div class="f-widget-link">
              <ul>
                <!-- Menu Link -->
                <li><a href="{% url 'website:privacy-policy' %}">Privacy Policy</a></li>
                <li><a href="{% url 'website:refund-policy' %}">Refund Policy</a></li>
                <li><a href="{% url 'website:Terms_and_condition' %}">Terms and Conditions</a></li>
               
              </ul>
            </div>
          </div>
        </div>
        <!-- to top -->
        <!--          <div class="cd-top"><i class="fas fa-level-up-alt"></i></div>-->
      </div>
    </div>
    
    <!-- .container end -->

    <!-- #footer bottom start -->
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="copyright">
            <p>
              ©2020 SOMANSH BACKOPS TEAM OF PROFESSIONLS
              <a href="http://www.sbtprofessionals.com" title="SBT Professionals" target="_blank">SBT Professionals</a>
            </p>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="text-right icon-round-white footer-social mt-25 mb-25">
            <a href="https://www.facebook.com/502482693270707?referrer=whatsapp" title="Facebook" target="blank"><i
                class="fab fa-facebook"></i></a>
            <a href="https://twitter.com/SBTProfessiona3?s=09" title="Twitter" target="blank"><i
                class="fab fa-twitter"></i></a>
            <a href="https://www.instagram.com/sbtprofessionals/" target="blank" title="Instagram"><i
                class="fab fa-instagram"></i></a>
            <a href="#" title="Google+" target="blank"><i class="fab fa-google-plus"></i></a>
            <a href="https://www.youtube.com/channel/UCflqm65LJjNPQvdUKYSRO9g" target="blank" title="Youtube"><i
                class="fab fa-youtube"></i></a>
          </div>
        </div>
      </div>
    </div>
    <!-- #footer bottom end -->
  </footer>

website/templates/website/includes/header.html
<style>
#header .navbar-brand img {
    max-height: 42px;
}
#header .navbar-default .navbar-nav>li>a {
    font-size: 12px;
    }
</style>
{% load static %}

<header id="header" class="transparent-header ">
    <div class="topheader top_header_light show-on-desktop-only">
      <div class="container">

        <div class="row">
          <div class="col-lg-7">
            <div class="address-icon">
              Register Your Business At SBT Professionals Platform, FREE
              FREE! Call us today<a href="#">+91 8295 393035</a>
            </div>
          </div>
          <div class="col-lg-5 text-right">
            <div class="custom-page-top">
              {% comment %} <a href="/sbt/download" class="search-ico-btn ico-btn">Download App</a> {% endcomment %}
              <a href="https://shorturl.at/hwILW" target="_blank" class="search-ico-btn ico-btn">Download App</a>
              <a href="{% url 'dashboard:login' %}" target="_blank">Branch Portal</a>
            </div>
            <!--
              <div class="social_top_header">

              </div> -->
          </div>
        </div>
      </div>
    </div>
    <!-- #navigation start -->
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      <strong>Message!</strong> {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close" aria-expanded="false">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}

    <nav class="navbar navbar-default navbar-expand-md navbar-light " id="navigation" data-offset-top="1">

      <!-- .container -->
      <div class="container  ">
        <!-- Logo and Menu -->
        <div class="navbar-header ">
          <div class="navbar-brand">
            <a href="/sbt/" title="SBT Professionals"><img src="{%static 'website/images/logo.png' %}"
                alt="Best Customer service " /></a>
          </div>
          <!-- site logo -->
        </div>
        <!-- Menu Toogle -->
        <div class="burger-icon">
          <div class="bar1"></div>
          <div class="bar2"></div>
          <div class="bar3"></div>
        </div>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="nav navbar-nav ml-auto">
            <div class="hide-on-desktop-only">
              {% if user.is_authenticated %}
            
              <div class="mt-4">

                <a class="dropdown-item" href="/sbt/logout/"><i class="fa fa-user"></i>Logout</a>

              </div>
              {% else %}

              <a class="cursor-on-pointer" style="margin-left: 30px;" href="/sbt/login" role="button"><i
                  class="fa fa-user"></i>
                Login/Register
              </a>
              {% endif %}


            </div>
         
            <!-- categories on mobile -->
            <li>
             
              <a href="/sbt/download" class="hide-on-desktop-only  search-ico-btn ico-btn"><i
                  class="fa fa-download" ></i> Download Our App</a>
                
                  
            </li>


            <li class="subnav ">

              <a href="/sbt/top">Team Of Professionals </a>

             
              <ul class="sub-menu">
                {% comment %} {% for vend in vendor|slice:"0:" %}
                <li>
                  <a href="/sbt/Topvendor/{{ vend.vendor_name }}">{{ vend.vendor_name }}</a>
                  {% if forloop.counter|divisibleby:0 and forloop.counter > 0 and not forloop.last%}
                </li> <a href=""></a>
                {% endif %}
                {% endfor %} {% endcomment %}
                {% for top in TOPS%}
                  <li>
                    <a href="{% url 'website:top-details' top.vendor_name%}">{{ top.vendor_name }}</a>
                  </li>
                {% endfor %}


              </ul>
            </li>
            <!-- </div> -->
            <!-- categories on mobile -->
            <li class="subnav">
              <a title="Shop" href="/sbt/trading">SBT Trading</a>
              <ul class="sub-menu">

                <li>
                  <a title="process" href="/sbt/process" class="nav-link">Our Process</a>
                </li>
                <li>
                  <a title="Faq" href="/sbt/FAQ" class="nav-link">FAQs?</a>
                </li>
                 
              </ul>
            </li>
<!--             <li><a href="#"  class="hide-on-desktop-only "> categories </a></li> -->

            <li><a title="List your Business" href="/sbt/become_a_vendor ">Become A Vendor</a></li>
          

            <li><a title="membership" href="/sbt/membership">Customer Membership</a></li>
            <li><a title="naukri" href="/sbt/jobs">Career</a></li>


          </ul>
          <div>
            <div class="custom-btn ml-4 show-on-desktop-only">
              {% if user.is_authenticated %}
              <div>
                <a href="/sbt/logout/" role="button"><i class="fa fa-user"></i>
                  Logout
                </a>
              </div>


              {% else %}
              <div>
                <a class="cursor-on-pointer mt-4" style="margin-left: 30px;" href="/sbt/login" role="button"><i
                    class="fa fa-user"></i>
                  Login/Register
                </a>
                {% endif %}
              </div>
            </div>
          </div>
          <!-- Menu Toogle end -->


        </div>
        <!-- .container end -->
    </nav>


    <!-- #navigation end -->

  </header>