dashboard/urls.py
from django.urls import path,include
from .views import index

from .views import login_view

from .views import *
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'dashboard'

urlpatterns =[
   path('', index, name = 'AdminHome'),
   path('search', search),
   path('login/', login_view, name="login"),
   # path('register/', register_user, name="register"),
   path("logout/", logout_view, name="logout"),
  

#   # class based views url routes
   path('new_branch/',NewBranchView.as_view(),name='NewBranch'), 
   path('all_branches/',AllBranchView.as_view(),name='AllBranches'), 
   path('branch_detail/<int:pk>/', DetailBranchView.as_view(), name='detail_branch'),
   path('profile_update/<int:pk>/', UpdateBranch.as_view(), name='branch_update'),
   path('branch_report/', BranchReportView.as_view(), name='branch_report'),

   path('all_employees/',AllEmployeeView.as_view(),name='AllEmployees'), 
   path('employee/<int:pk>/', DetailEmployeeView.as_view(), name='employee_detail'),

   
   path('new_category/',NewcategoryView.as_view(),name='NewCategory'), 
   path('all_category/',AllCategoriesView.as_view(),name='AllCategory'), 
   path('<int:pk>/', DetailCategoryView.as_view(), name='category_detail'),
  

   path('all_vendors/',AllVendorsView.as_view(),name='AllVendors'), 
   path('vendor/<int:pk>/', DetailVendorView.as_view(), name='vendor_detail'),

   
   path('all_customers/',AllCustomerView.as_view(),name='AllCustomer'), 
   path('customer/<int:pk>/', DetailCustomerView.as_view(), name='customer_detail'),


   path('all_resumes/',AllResumeView.as_view(),name='AllResumes'), 
   path('new_banner/',NewBannerView.as_view(),name='NewBanner'), 
   path('new_banner_2/',NewBanner2View.as_view(),name='NewBanner2'), 
   path('all_banners/',AllBannerView.as_view(),name='AllBanners'), 
   path('all_banners_2/',AllBanner2View.as_view(),name='AllBanners2'), 
   path('download/',download_resume,name='Download'), 


   #for contact
   path('contact/',ContactUsView.as_view(),name='contact'), 
   

  # for template testing
   # path('test_view/',TestView.as_view(),name='NewTest'),

  
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sbt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path
from restapi.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', lambda r: HttpResponseRedirect('sbt/')),
    path('sbt/', include('website.urls')),
    path('auth/', include('authentication.urls')),
    path('api/', include('restapi.urls',namespace='rest_api')),
    path('vendor/', include('Vendor.urls')),
    path('employee/', include('Employee.urls',namespace='employee')),
    path('customer/', include('Customer.urls')),
    path('sbtadmin/', include('dashboard.urls',namespace='dashboard')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = 'website.views.error_404_view'

dashboard/models.py
from dashboard.forms import ContactForm
from website.models import *

from django.db import models
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth import get_user_model
User = get_user_model()

GENDER_CHOICES = (
    ("1", "Please Select"),
    ("2", "Male"),
    ("3", "Female"),
    ("4", "Other"),

)

STATUS_CHOICES = (
    ("1", "Please Select"),
    ("2", "New"),
    ("3", "Verified"),

)

VALID_STATE_CHOICES = (
    ("1", "Please Select"),
    ("2", "Andra Pradesh"),
    ("3", "Arunachal Pradesh"),
    ("4", "Assam"),
    ("5", "Bihar"),
    ("6", "Chhattisgarh"),
    ("7", "Chandigarh"),
    ("8", "Dadar and Nagar Haveli"),
    ("9", "Daman and Diu"),
    ("10", "Delhi"),
    ("11", "Goa"),
    ("12", "Gujarat"),
    ("13", "Haryana"),
    ("14", "Himachal Pradesh"),
    ("15", "Jammu and Kashmir"),
    ("16", "Jharkhand"),
    ("17", "Karnataka"),
    ("18", "Kerala"),
    ("19", "Lakshadeep"),
    ("20", "Madya Pradesh"),
    ("21", "Maharashtra"),
    ("22", "Manipur"),
    ("23", "Meghalaya"),
    ("24", "Mizoram"),
    ("25", "Nagaland"),
    ("26", "Orissa"),
    ("27", "Punjab"),
    ("28", "Pondicherry"),
    ("29", "Rajasthan"),
    ("30", "Sikkim"),
    ("31", "Tamil Nadu"),
    ("32", "Telagana"),
    ("33", "Tripura"),
    ("34", "Uttaranchal"),
    ("35", "Uttar Pradesh"),
    ("36", "West Bengal"),
    ("37", "Andaman and Nicobar Island"),

)

"""class UserType(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    is_branch_user = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)"""

BRANCH_TYPE_CHOICES = (
    ("root", "root"),
    ("state", "state"),
    ("district", "district"),
    ("tehsil", "tehsil"),
    ("village", "village"),

)


# Create your models here.
class Branch(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE,null= True, blank=True)
    branch_type = models.CharField(max_length=100,choices=BRANCH_TYPE_CHOICES,blank=True, null=True)
    branch_name = models.CharField(max_length=20,default='')
    Mobile_No = models.CharField(max_length=20,blank=True, null=True)
    Mobile_No_2 = models.CharField(max_length=20,blank=True, null=True)
    Address1 = models.CharField(max_length=100, default='')
    Address2 = models.CharField(max_length=100, blank=True, null=True, default='')
    city = models.CharField(max_length=100, default='')
    state = models.CharField(max_length=100, choices=VALID_STATE_CHOICES, default='Please Select')
    zipcode = models.IntegerField()
    country = CountryField()
    EmailID = models.EmailField(null=True, blank=True)
    regsitration_date = models.DateTimeField(auto_now_add=True)
    landline_no = models.CharField(max_length=15,null=True, blank=True)
    Longitude = models.FloatField(null=True, blank=True)
    Latitude = models.FloatField(null=True, blank=True)
    extra_Info = models.TextField(max_length=200, blank=True, null=True)
    Contact_Person = models.CharField(max_length=100, default='', blank=True, null=True)
    branch_is_active = models.BooleanField(default=False)
    Image = models.ImageField(upload_to="dashboard/images/branch", blank=True,null=True)
    

    def __str__(self):
        return self.branch_name




class Banner(models.Model):
    banner_id = models.AutoField(primary_key=True)
    banner_name = models.CharField(max_length=50,default='')
    banner_img = models.ImageField(upload_to="dashboard/images/banner_1")

    def __str__(self):
        return self.banner_name


class Banner2(models.Model):
    banner_id = models.AutoField(primary_key=True)
    banner_name = models.CharField(max_length=50,default='')
    banner_img = models.ImageField(upload_to="dashboard/images/banner_2")

    def __str__(self):
        return self.banner_name
    

class BranchReport(models.Model):
    branch = models.ForeignKey(Branch,on_delete=models.CASCADE)
    submit_time = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    report_detail = models.TextField(max_length=5000)


    def __str__(self):
        return str(self.branch) + ' branch submit report at ' + str(self.submit_time)

class BranchContact(models.Model):
    branch = models.ForeignKey(Branch,on_delete=models.CASCADE)
    submit_time = models.DateTimeField(auto_now_add=True)
    email = models.CharField(max_length=100)
    desc = models.TextField(max_length=5000)


    def __str__(self):
        return str(self.branch) + ' contacts at ' + str(self.submit_time)

dashboard/views.py
import json
from os import access
import pathlib
from django.db import reset_queries

import requests
from Customer.models import Customer
# from django.views.generic.edit import FormView
from django.contrib import messages
# #from authentication app
# #from app
# from website.models import *
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import Group
from django.core import exceptions
from django.db.models import Q
from django.db.models.aggregates import Avg
# from django.forms.utils import ErrorList
from django.http import HttpResponse
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
# from django.views.generic import TemplateView
from django.views import View, generic
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from Employee.models import Employee
from requests.api import request
from Vendor.models import Vendor

from .forms import *
# #functions
from .functions import *
# #models
from .models import *

# from django.shortcuts import render, get_object_or_404, redirect
# from django.template import loader
# from django.http import HttpResponse
# from django import template

# from django.core.mail import send_mail
# # Create your views here.

User = get_user_model()


fn = pathlib.Path(__file__).parent.parent / 'config.json'
with open(fn,"r") as params:
    parameters = json.load(params)
api_key = parameters['key']

def search(request):
    if request.is_ajax():
        query = request.GET.get('query')
        obj = Branch.objects.filter(Q(branch_name__icontains = query) | Q(user__phone__icontains = query))
        data = list()
        for branch in obj:
            data.append({
               'phone': branch.user.phone,
               'branch_name': branch.branch_name,
               'Mobile_No': branch.Mobile_No,
               'city': branch.city,
               'state': branch.state,
               'EmailID': branch.EmailID,
            })
        data = json.dumps(data)
        print(data)
        return JsonResponse({'rv':query, 'obj':data})

    
        
            
        
        
def login_view(request):
    print('......POST')
    if request.method == "POST":
        print('......POST')
        loginusername = request.POST.get("phone")
        loginpassword = request.POST.get("password")
        print(loginusername)
        print(loginpassword)
        user = User.objects.get(phone=loginusername)
        user.check_password(loginpassword)
        if user is not None and user.is_staff:
            branch_user = Branch.objects.get(user=user)
            print(branch_user)
            login(request, user)
            messages.success(request, 'Login Successful!')
            return redirect('dashboard:AdminHome')
        else:    
            return HttpResponse('Invalid credentials')  
    return render(request, "dashboard/accounts/auth-login.html")
            

        
def logout_view(request):
    logout(request)
    messages.success(request, 'Logged Out Successfully!')
    return redirect('dashboard:login')      
             
          



@login_required(login_url="/sbtadmin/login/") 
def index(request):
    branch_user = Branch.objects.filter(user=request.user).first()
    customers = Customer.objects.all()
   
    c_count =  customers.count()

    vendors = Vendor.objects.all()
    v_count =  vendors.count()
    
   
    active_vendors = Vendor.objects.filter(vendor_is_active=True)
    active_vendor_count = active_vendors.count()

    active_customers = Customer.objects.filter(customer_is_active=True)
    active_customer_count = active_customers.count()
    

    # if slug == api_key:
    return render(request, "dashboard/index.html",{'active_customers':active_customer_count,'active_vendors':active_vendor_count,'branch':branch_user,'user':request.user,'customers':c_count,'vendors':v_count})
    # else:
        # return HttpResponse('not allowed to access')


# # @login_required(login_url="/sbtadmin/login/")
# def profile(request):
#     return render(request, "dashboard/profile.html")

class NewBranchView(View):
    """
    Save Branch Form to database
    TODO:Send Generated ID and Password Of Branch
    TODO:check if branch with a user already exists

    """
    template_name = "dashboard/forms/NewBranchForm.html"
    initial = {'key': 'value'}
    form_class = NewBranchForm
    
    def get(self, request, *args, **kwargs):
        branch_user = Branch.objects.filter(user=request.user).first()
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form,'branch':branch_user})

    def post(self, request, *args, **kwargs):
        branch_user = Branch.objects.filter(user=request.user).first()
        form = self.form_class(request.POST)
        if form.is_valid():
            # <process form cleaned data>
            new_branch = Branch()
            response = check_if_branch_already_exists(form.cleaned_data['branch_name'])
            if response != None:
                messages.info(request,'Branch Already exists')
                # return HttpResponse('branch already exists')
                return redirect('dashboard:NewBranch')
             
            new_branch.branch_name = form.cleaned_data['branch_name']
            new_branch.branch_type = form.cleaned_data['branch_type']
            new_branch.Mobile_No = form.cleaned_data['mobile_no']
            new_branch.Mobile_No_2 = form.cleaned_data['mobile_no_2']
            new_branch.Address1 = form.cleaned_data['branch_address']
            new_branch.Address2 = form.cleaned_data['branch_address_2']
            new_branch.city = form.cleaned_data['branch_city']
            new_branch.state = form.cleaned_data['branch_state']
            new_branch.zipcode = form.cleaned_data['zip_code']
            new_branch.country = form.cleaned_data['branch_country']
            new_branch.EmailID = form.cleaned_data['branch_email_address']
            new_branch.regsitration_date = form.cleaned_data['regsitration_date']
            new_branch.landline_no = form.cleaned_data['landline_number']
            new_branch.extra_Info = form.cleaned_data['extra_info']
            new_branch.Contact_Person = form.cleaned_data['branch_contact_person']
            new_branch.branch_is_active = form.cleaned_data['branch_is_active']
            new_branch.Image = form.cleaned_data['branch_img']
            if new_branch.branch_is_active:
                from django.contrib.auth.hashers import make_password
                branch_user = User.objects.filter(phone=form.cleaned_data['mobile_no']).first()
                print(branch_user)  
                if branch_user != None:   
                    branch_user.set_password(make_password(password_genrator()))
                    branch_user.is_staff = True
                    branch_user.is_branch_user = True
                    branch_group = Group.objects.get(name='branch')
                    branch_group.user_set.add(branch_user) 
                    # district_group = Group.objects.get(name='district')
                    # district_group.user_set.add(district_group) 
                    branch_user.save()
                    new_branch.user = branch_user
                    new_branch.save()  
                    password = password_genrator()
                    url = f"http://sendsms.designhost.in/index.php/smsapi/httpapi/?uname=sbtpro&password=123456&sender=SBTPRO&receiver={branch_user.phone}&route=TA&msgtype=1&sms=Your USER ID = {branch_user.phone}\n password is {password}"
                    response = requests.request("GET",url)
                    print(response)
                    messages.success(request,'New Branch Created!')
                    return redirect('dashboard:AdminHome')
                else:
                    branch_user = User.objects.create(phone=new_branch.Mobile_No)
                
                    password = password_genrator()
                    print('...............',password)
                    url = f"http://sendsms.designhost.in/index.php/smsapi/httpapi/?uname=sbtpro&password=123456&sender=SBTPRO&receiver={branch_user.phone}&route=TA&msgtype=1&sms=Your USER ID = {branch_user.phone}\n password is {password}"
                    response = requests.request("GET",url)
                    print(response)
                    branch_user.is_staff = True
                    branch_user.is_branch_user = True
                    branch_user.set_password(make_password(password_genrator()))
                    branch_group = Group.objects.get(name='branch')
                    branch_group.user_set.add(branch_user) 
                    branch_user.save()
                    new_branch.user = branch_user
                    new_branch.save()
                    messages.success(request,'New Branch Created!')
                    return redirect('dashboard:AdminHome')
        # return render(request, self.template_name, {'form': form})
           
    
    
class AllBranchView(generic.ListView):
    """
    Display All Branches From Database
    """
    model = Branch
    paginate_by = 10
    template_name = 'dashboard/ViewsAll/all_branches.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class DetailBranchView(DetailView):
    model = Branch
    fields = '__all__'
    template_name = 'dashboard/accounts/profile.html'
    def get_context_data(self, **kwargs):
        # branch_user = Branch.objects.filter(user=self.user)
        context = super().get_context_data(**kwargs)
        # context['branch'] = branch_user
        return context


class UpdateBranch(View):
    """
    docstring
    """
    def post(self, request, *args, **kwargs):

dashboard/templates/dashboard/ViewsAll/all_categories.html
{% extends "dashboard/layout/base.html" %} {% block title %}
<title>All Categories - Dashboard SBTProfessionals</title>
{% endblock title %} {% block maincontent %}


<!-- begin app-main -->
<div class="app-main" id="main">
    <!-- begin container-fluid -->
    <div class="container-fluid">
        <!-- begin row -->
        <div class="row">
            <div class="col-md-12 m-b-30">
                <!-- begin page title -->
                <div class="d-block d-sm-flex flex-nowrap align-items-center">
                    <div class="page-title mb-2 mb-sm-0">
                        <h1>All Categories</h1>
                    </div>
                    <div class="ml-auto d-flex align-items-center">
                        <nav>
                            <ol class="breadcrumb p-0 m-b-0">
                                <li class="breadcrumb-item">
                                    <a href="index.html"><i class="ti ti-home"></i></a>
                                </li>
                                <li class="breadcrumb-item">
                                    Categories
                                </li>
                                <li class="breadcrumb-item active text-primary" aria-current="page">View All Categories</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <!-- end page title -->
            </div>
        </div>
        <!-- end row -->
        <!-- begin row -->

        <div class="col-12 col-md-6 col-lg-12">
            <div class="card card-statistics">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Title</th>
                                    <th scope="col">Desc.</th>
                                    <th scope="col">Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for category in object_list %}
                                <tr>
                                    <td style="color: black;"> <strong>{{ category.category_name }}</strong></td>
                                    <td>{{ category.category_description }}</td>
                                    <td><a type="button" href="{% url 'dashboard:category_detail' category.category_id %}" class="btn btn-inverse-success">View</a></td>
                                </tr>
                                {% if forloop.counter|divisibleby:1 and forloop.counter > 0 and not forloop.last%}
                                <tr> </tr>
                                {% endif %} {% empty %}
                                <li>No Categories yet.</li>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->
</div>
<!-- end container-fluid -->
</div>
<!-- end app-main -->
</div>
<!-- end app-container -->
{% endblock maincontent %}

dashboard/templates/dashboard/ViewsAll/all_customer.html
{% extends "dashboard/layout/base.html" %} {% block title %}
<title>All Customers - Dashboard SBTProfessionals</title>
{% endblock title %} {% block maincontent %}


<!-- begin app-main -->
<div class="app-main" id="main">
    <!-- begin container-fluid -->
    <div class="container-fluid">
        <!-- begin row -->
        <div class="row">
            <div class="col-md-12 m-b-30">
                <!-- begin page title -->
                <div class="d-block d-sm-flex flex-nowrap align-items-center">
                    <div class="page-title mb-2 mb-sm-0">
                        <h1>All Customers</h1>
                    </div>
                    <div class="ml-auto d-flex align-items-center">
                        <nav>
                            <ol class="breadcrumb p-0 m-b-0">
                                <li class="breadcrumb-item">
                                    <a href="index.html"><i class="ti ti-home"></i></a>
                                </li>
                                <li class="breadcrumb-item">
                                    Customers
                                </li>
                                <li class="breadcrumb-item active text-primary" aria-current="page">View All Customers</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <!-- end page title -->
            </div>
        </div>
        <!-- end row -->
        <!-- begin row -->

        <div class="col-12 col-md-6 col-lg-12">
            <div class="card card-statistics">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">User Phone</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Address</th>
                                    <th scope="col">Joinig date</th>
                                    <th scope="col">Active</th>
                                    <th scope="col">Subscription plan</th>
                                    <th scope="col">Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for customer in object_list %}
                                <tr>
                                    <td style="color: black;"> <strong>{{ customer.user }}</strong></td>
                                    <td style="color: black;"> <strong>{{ customer.customer_name }}</strong></td>
                                    <td style="color: black;"> <strong>{{ customer.Address }}</strong></td>
                                    <td>{{ customer.joining_date }}</td>
                                    <td>{{ customer.customer_is_active }}</td>
                                    <td>{{ customer.subscription_plan_taken }}</td>
                                    <td><a href="{% url 'dashboard:customer_detail' customer.customer_id %}" class="btn btn-inverse-success">View</a></td>
                                </tr> 
                                {% if forloop.counter|divisibleby:1 and forloop.counter > 0 and not forloop.last%}
                                <tr> </tr>
                                {% endif %} {% empty %}
                                <li>No Customer yet.</li>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="pagination">
            <span class="step-links">
        {% if page_obj.has_previous %}
        <strong><a href="?page=1">&laquo; first</a></strong>
       <strong style="color: black;"> <a  href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-backward"></i> Previous</a></strong>
        {% endif %}
        
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span> {% if page_obj.has_next %}
            <strong style="color: black;"><a href="?page={{ page_obj.next_page_number }}">Next <i class="fa fa-forward"></i> </a></strong>
            <strong><a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> </strong>{% endif %}
            </span>
        </div>
    </div>
</div>
<!-- end row -->
</div>
<!-- end container-fluid -->
</div>
<!-- end app-main -->
</div>
<!-- end app-container -->
{% endblock maincontent %}

dashboard/templates/dashboard/ViewsAll/all_resumes.html
{% extends "dashboard/layout/base.html" %} {% block title %}
<title>All Resumes - Dashboard SBTProfessionals</title>
{% endblock title %} {% block maincontent %}


<!-- begin app-main -->
<div class="app-main" id="main">
    <!-- begin container-fluid -->
    <div class="container-fluid">
        <!-- begin row -->
        <div class="row">
            <div class="col-md-12 m-b-30">
                <!-- begin page title -->
                <div class="d-block d-sm-flex flex-nowrap align-items-center">
                    <div class="page-title mb-2 mb-sm-0">
                        <h1>All Resumes</h1>
                    </div>
                    <div class="ml-auto d-flex align-items-center">
                        <nav>
                            <ol class="breadcrumb p-0 m-b-0">
                                <li class="breadcrumb-item">
                                    <a href="index.html"><i class="ti ti-home"></i></a>
                                </li>
                                <li class="breadcrumb-item">
                                    Resumes
                                </li>
                                <li class="breadcrumb-item active text-primary" aria-current="page">View All Resumes</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <!-- end page title -->
            </div>
        </div>
        <!-- end row -->
        <!-- begin row -->

        <div class="col-12 col-md-6 col-lg-12">
            <div class="card card-statistics">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Name</th>
                                    <th scope="col">Filling DAte</th>
                                    <th scope="col">Resume</th>
                                    <th scope="col">Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for resume in object_list %}
                                <tr>
                                    <td> <strong>{{ resume.name }}</strong></td>
                                    <td>{{ resume.filling_date }}</td>
                                    <td>
                                        <iframe src="/media/website/JobResume/{{ resume.Resume }}" height="200" width="300"></iframe>
                                        <!-- <a href="/media/website/JobResume/{{ resume.Resume }}"></a> -->
                                    </td>
                                    <td><a href="{% url 'dashboard:Download' %}"><button  class="btn btn-inverse-success">View</button></a> </td>
                                </tr>
                                {% if forloop.counter|divisibleby:1 and forloop.counter > 0 and not forloop.last%}
                                <tr> </tr>
                                {% endif %} {% empty %}
                                <li>No Resumes yet.</li>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->
</div>
<!-- end container-fluid -->
</div>
<!-- end app-main -->
</div>
<!-- end app-container -->
{% endblock maincontent %}